### ISSUE TITLE
{"errorMessage": "Unable to import module 'app'"} when using IOpipe with Chalice

### ISSUE THREAD

**Issue by adjohn** [iopipe/iopipe-python#11]
I'm getting the following error when running a Lambda with IOpipe+Chalice
`{"errorMessage": "Unable to import module 'app'"}`

This can be replicated by using the standard "Hello World" app from Chalice

```
@iopipe.decorator
@app.route('/')
def index():
    return {'hello': 'world'}
```

**Comment by ewindisch** [comment]
Thing is that if we put the decorator under @app.route, we won't get the right arguments in the expected order.

I don't think it's working with being *above* the Chalice decorator either.

**Comment by kolanos** [comment]
The agent now supports Chalice in v0.9.1. Although the code above still won't work because the agent needs to wrap the app and not be used as a decorator for routes.
