### ISSUE TITLE
use botocore.vendored.requests instead of implying an app depedency

### ISSUE THREAD

**Issue by kapilt** [iopipe/iopipe-python#18]
given the execution environment, adding an additional dependency seems extraneous, given the platform already has the underlying library just by switching the import location. perhaps not meaningful given the common installation of this library, but worth a consideration.

**Comment by kapilt** [comment]
hmm.. also perhaps obsoleted by the pr that incorporates boto3 invokelambda for delivery.

**Comment by ewindisch** [comment]
I want to keep both methods of reporting -- using the existing vendored libraries is definitely a good idea!
