### ISSUE TITLE
Log plugin should use SerDe compatible format

### ISSUE THREAD

**Issue by ewindisch** [iopipe/iopipe-python#196]
For flexibility of querying from Athena we should use a SerDe compatible format:

https://docs.aws.amazon.com/athena/latest/ug/supported-format.html

Supported formats are CSV, Tab-separated values, JSON, Parquet (fast!!!), Logstash, Apache, and CloudTrail.

**Comment by kolanos** [comment]
@ewindisch And what columns? Are the current ones sufficient?

**Comment by kolanos** [comment]
Relevant documentation: https://docs.aws.amazon.com/athena/latest/ug/json.html
