### ISSUE TITLE
Inconsistency between environment variables for agents

### ISSUE THREAD

**Issue by XerTheSquirrel** [iopipe/iopipe-python#220]
Okay while looking at the Java code I discovered that at least for the profiler plugin there is an inconsistent use of environment variables between the agents.

 * Java: `IOPIPE_PROFILER_ENABLE`
 * Python: `IOPIPE_PROFILER_ENABLED`
 * Javascript: `IOPIPE_ENABLE_PROFILER`

I have an issue open for the Java agent here: https://github.com/iopipe/iopipe-java/issues/64 .

**Comment by kolanos** [comment]
@XerTheSquirrel The preference is to be consistent with `IOPIPE_ENABLED`. So in this case `IOPIPE_PROFILER_ENABLED` is the preferred environment variable to use.
