### ISSUE TITLE
Differentiate prefix for plugin autolabels and aws service autolabels

### ISSUE THREAD

**Issue by katiebayes** [iopipe/iopipe-python#228]
@kolanos This will help me make the autolabels a little clearer on the frontend. I'd suggest keeping the `@iopipe` but having the prefix be `@iopipe-plugin/` for plugins and `@iopipe-aws/` for aws services.  I'd prefer to keep some similarity among all autolabels to quickly split them from user labels, so that's the `@iopipe`.

Thank you!!

**Comment by kolanos** [comment]
@katiebayes The `@iopipe/` acts as a namespace, which signals that a label came from IOpipe. We use `@iopipe/` elsewhere, like in the event info plugin. Would something like `@iopipe/plugin-` and `@iopipe/aws-` work as well? For `@iopipe/plugin-` or whatever, does this become `@iopipe/plugin-event-info`? With `@iopipe/api-gateway` become `@iopipe/aws-api-gateway` or should it be `@iopipe/plugin-aws-api-gateway`?
