### ISSUE TITLE
Provide mock IOpipe for user function tests

### ISSUE THREAD

**Issue by ewindisch** [iopipe/iopipe-python#233]
Users developing with IOpipe will find that calls to context.iopipe.* will fail without a good mock. We should provide a reasonable mock for those users so they do not need to build this themselves.

**Comment by kolanos** [comment]
@ewindisch Can you provide an example of where `context.iopipe.*` fails? Just so I understand the use case.

**Comment by kolanos** [comment]
Closing s related to #285.
