### ISSUE TITLE
Python profiling auto-labels are not showing up

### ISSUE THREAD

**Issue by adjohn** [iopipe/iopipe-python#261]
Profiling is enabled, and I can download profiles, but labels are not showing up in the dashboard.

**Steps to reproduce the issue:**
1. Setup a function with profiling enabled
2. Log into the dashboard and see no labels.

**Comment by kolanos** [comment]
Fixed https://github.com/iopipe/iopipe-python/commit/ed3c22c2e622ae80257a9db50c4211c687721720
