### ISSUE TITLE
Layer Acceptance Tests

### ISSUE THREAD

**Issue by kolanos** [iopipe/iopipe-python#292]
Add acceptance tests for SAM and Serverless using Lambda Layers.

**Comment by kolanos** [comment]
Layer acceptance tests for Serverless are available here: https://github.com/iopipe/iopipe-python/tree/master/acceptance/serverless-layers

**Comment by adjohn** [comment]
It looks like these are not getting updated automatically with the latest Layer versions.

**Comment by kolanos** [comment]
Closing as Serverless acceptance tests are in place.
