### ISSUE TITLE
context.iopipe.error() itself raises an error during lambda execution

### ISSUE THREAD

**Issue by majorgilles** [iopipe/iopipe-python#296]
**Description**

context.iopipe.error() itself raises an error during lambda execution

**Steps to reproduce the issue:**
1. use the lambda handler's context object
2. catch an exception and use "context.iopipe.error(the_exception)

**Describe the results you received:**

...
...
File "/var/task/common/utils/response_builders.py", line 12, in _build_error_response
    context.iopipe.error(exception)
  File "/var/task/iopipe/context.py", line 91, in error
    self.instance.run_hooks("pre:report")
  File "/var/task/iopipe/agent.py", line 233, in run_hooks
    [hooks[name](p) for p in self.plugins if p.enabled]
  File "/var/task/iopipe/agent.py", line 233, in <listcomp>
    [hooks[name](p) for p in self.plugins if p.enabled]
  File "/var/task/iopipe/agent.py", line 228, in <lambda>
    "pre:report": lambda p: p.pre_report(self.report),
  File "/var/task/iopipe/contrib/logger/plugin.py", line 93, in pre_report
    self.signed_request = self.signed_request.result()
AttributeError: 'dict' object has no attribute 'result'

**Describe the results you expected:**
My own caught exception clearly indicated visually inside the iopipe dashboard.

**Additional information you deem important (e.g. issue happens only occasionally):**
pipfile dependencies:

requests = "==2.20.0"
boto3 = "==1.9.37"
ptvsd = "==4.1.4"
pydantic = "==0.16.1"
vininfo = "==0.3.0"
**iopipe = "==1.7.8"**
lizy-common = "==0.2.7"
requests-aws4auth = "==0.9"

npm:

"serverless": "^1.32.0"

**Comment by vincestus** [comment]
**Description**
I'm trying to centralise the http request processing in a common function `process_http_request` used by my different handlers and have a similar problem with the usage of `context.io_pipe.error(error)` in that function. The code structure looks like this:

```
@io_pipe.decorator
def handler(event, context):
    return process_http_request(event, context, success_create_vehicle)

def process_http_request(event, context, success_function) -> Dict:
    try:
        function_call()
    except ValidationError as error:
        context.io_pipe.error(error)
```

**Describe the results you received:**

The error is the following one:

```
File "...", line 41, in process_http_request
    context.io_pipe.error(error)
  File "/var/task/iopipe/context.py", line 15, in __getattr__
    return getattr(self.base_context, name)
AttributeError: 'LambdaContext' object has no attribute 'io_pipe'
```

I have tried by using the `@io_pipe` decorator on the process_http_request function itself but then I have the following error:

```
Traceback (most recent call last):
  File "/var/task/iopipe/agent.py", line 149, in wrapped
    result = func(event, context)
  File "...", line 30, in handler
    return process_http_request(event, context, success_create_vehicle)
TypeError: wrapped() takes 2 positional arguments but 3 were given
```

**Comment by kolanos** [comment]
@majorgilles Thanks for the bug report.

Looking at this:

```
File "/var/task/iopipe/contrib/logger/plugin.py", line 93, in pre_report 
self.signed_request = self.signed_request.result() 
AttributeError: 'dict' object has no attribute 'result' 
```

This is unusual, as `self.signed_request` should be a `Future`. I can add a check here for the `result()` method, but do you know how this is not a `Future`?

As a workaround, I would disable the `Logger` plugin, as that's the plugin causing the error.

**Comment by kolanos** [comment]
@vincestus Thanks for the bug report. In the future, please create a new issue.


As for your example code, this line:

```
context.io_pipe.error(error)
```

Should be:

```
context.iopipe.error(error)
```

The `context.iopipe` doesn't derive it's name from the decorator instance's name.

**Comment by vincestus** [comment]
@kolanos thanks for the fast answer. I updated the coded but still run into the following error:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/iopipe/agent.py", line 149, in wrapped
    result = func(event, context)
  File "...", line 30, in handler
    return process_http_request(event, context, success_create_vehicle)
  File "...", line 41, in process_http_request
    context.iopipe.error(error)
  File "/var/task/iopipe/context.py", line 91, in error
    self.instance.run_hooks("pre:report")
  File "/var/task/iopipe/agent.py", line 233, in run_hooks
    [hooks[name](p) for p in self.plugins if p.enabled]
  File "/var/task/iopipe/agent.py", line 233, in <listcomp>
    [hooks[name](p) for p in self.plugins if p.enabled]
  File "/var/task/iopipe/agent.py", line 228, in <lambda>
    "pre:report": lambda p: p.pre_report(self.report),
  File "/var/task/iopipe/contrib/logger/plugin.py", line 90, in pre_report
    if self.signed_request is not None:
AttributeError: 'LoggerPlugin' object has no attribute 'signed_request'
```

**Comment by vincestus** [comment]
@kolanos thanks for the fast reaction.

**Comment by kolanos** [comment]
@vincestus Found the problem. Basically the codepath for `context.iopipe.error()` was calling the `post:invoke` hook after reporting. Because `self.signed_request` was dependent on this hook, the reporting was checking for a future that didn't yet exist. I've reordered the logger plugin execution flow in the PR. Thanks again for the report.

**Comment by kolanos** [comment]
@vincestus Likely today or tomorrow.
