### ISSUE TITLE
logger plugin Recursion issues

### ISSUE THREAD

**Issue by lordmuffin** [iopipe/iopipe-python#299]
So I have Lambda function with IOPipe included within it, and it calls a few things, primarily LoggerPlugin.  When it runs and hits the first print statement, it throws python into an unrecoverable recursion loop.

Has anyone else seen this?

Source Code: https://github.com/AMILookup/amilookup.com-infra/blob/develop/functions/ami_lookup/ami_lookup.py

Error:

{
  "errorMessage": "maximum recursion depth exceeded",
  "errorType": "RecursionError",
  "stackTrace": [
    "  File \"/var/task/iopipe/agent.py\", line 162, in wrapped\n    raise e\n",
    "  File \"/var/task/iopipe/agent.py\", line 149, in wrapped\n    result = func(event, context)\n",
    "  File \"/var/task/ami_lookup.py\", line 73, in lambda_handler\n    print(\"Got event\\n\" + json.dumps(event, indent=2))\n",
    "  File \"/var/task/iopipe/contrib/logger/stream.py\", line 7, in write\n    self.logger.info(line.rstrip())\n",
    "  File \"/var/lang/lib/python3.7/logging/__init__.py\", line 1383, in info\n    self._log(INFO, msg, args, **kwargs)\n",
    "  File \"/var/lang/lib/python3.7/logging/__init__.py\", line 1519, in _log\n    self.handle(record)\n",
    "  File \"/var/lang/lib/python3.7/logging/__init__.py\", line 1529, in handle\n    self.callHandlers(record)\n",
    "  File \"/var/lang/lib/python3.7/logging/__init__.py\", line 1591, in callHandlers\n    hdlr.handle(record)\n",
    "  File \"/var/lang/lib/python3.7/logging/__init__.py\", line 905, in handle\n    self.emit(record)\n",
    "  File \"/var/runtime/bootstrap.py\", line 257, in emit\n    print(msg)\n",

**Comment by kolanos** [comment]
@lordmuffin Thanks for the bug report. Looking into it.

**Comment by kolanos** [comment]
@lordmuffin Having trouble reproducing this. If you set `LoggerPlugin(enabled=True, redirect_stdout=False)` does the error go away?

**Comment by lordmuffin** [comment]
@kolanos  First of all, thanks for working on this I really appreciate the help here.

Yes i added ```redirect_stdout=False``` and the issue goes away and my lambda proceeds as expected.  Any idea why this is the case?

**Comment by kolanos** [comment]
@lordmuffin No problem . Happy to help.

As for what's going on, the `redirect_stdout` setting does this: https://github.com/iopipe/iopipe-python/blob/master/iopipe/contrib/logger/plugin.py#L102

But if you're already sending `sys.stdout` to the Python `logging` module, or vice-versa, then it's possible the wrapping that the line above does ends up making that write recursive. Although I haven't been able to reproduce as of yet. I noticed a `import sys` in your link, is that in use somewhere? And can I see how you have logging configured?

**Comment by lordmuffin** [comment]
What you see is what you get in that code.  Thats all my function consists of, plus the imported IOPipe libraries.  The ```import sys``` seems to be old from something I must have done earlier (iterated on this a lot.)  My logging mechanism is currently just printing out, and that works fine for CloudWatch logs.  But clearly here its causing us an issue.

**Comment by kolanos** [comment]
@lordmuffin When you do `redirect_stdout=False`, do you still see the `print()` messages in your logs? Either in CloudWatch, your IOpipe invocation view or both?

**Comment by kolanos** [comment]
@lordmuffin Ok, thanks. Will investigate further.

**Comment by lordmuffin** [comment]
@kolanos This is great thank you!  When is the next release planned?  Or does it makes sense for me to pull down the master branch?
