### ISSUE TITLE
Python 3.6, Serverless framework, Logger plugin: no log messages appear on the io_pipe website

### ISSUE THREAD

**Issue by majorgilles** [iopipe/iopipe-python#302]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**
With the serverless framework, python 3.6, logger plugin enabled, I cannot see any log messages in the logs tab of an invocation on the iopipe website.

iopipe-python release: v1.7.11

**Steps to reproduce the issue:**
1. client is instantiated via io_pipe = IOpipe(io_pipe_token, plugins=[LoggerPlugin(), EventInfoPlugin()])
2. in the code, logging.info(""), logging.error("") are used instead of context.iopipe... (to avoid sprinkling vendor specific code inside of our code base) 

**Describe the results you received:**
when checking invocations in iopipe, nothing appears on the website (but they do with iopipe = "==1.7.8", so something has been broken)

**Comment by majorgilles** [comment]
Ok. I've noticed an extremely annoying behaviour. The logger plugin reraises the error it has received as a parameter. Please make it an optional behaviour... This is more than annoying.

**Comment by kolanos** [comment]
@majorgilles Not sure what you mean. Can you provide a code example of this behavior?

**Comment by kolanos** [comment]
@majorgilles `context.iopipe.error()` is meant to capture an exception in the report. If you just want to capture the traceback but not re-raise, then `context.iopipe.log.exception()` can do that, which is the `logging` module's implementation.

If you have a good use case, we can consider adding a flag to `context.iopipe.error()` to not re-rraise the exception. But don't think this should be default behavior as many lambda workflows depend on an exception being raised, such as a lambda retrying an invocation.

`context.iopipe.error()` is run when there's an uncaught exception and reports immediately.

**Comment by majorgilles** [comment]
Thanks for your feedback. That makes perfect sense when used from within
your own wrapper. I found an alternative combining labels and metrics that
offers me more granular control in terms of alerts, so there's no real need
to change this in the end.

Le mer. 23 janv. 2019 à 16:09, Michael Lavers <notifications@github.com> a
écrit :

**Comment by kolanos** [comment]
@majorgilles Glad to hear you found a solution. Please let us know if you have any other issues. Thanks.
