### ISSUE TITLE
No logs are registered in 1.7.13 with the logger plugin enabled

### ISSUE THREAD

**Issue by majorgilles** [iopipe/iopipe-python#307]
Things were working fine in 1.7.11 (logs do appear in the logs tab on the iopipe website), but not in 1.7.13

the client is instantiated like this:
```python
 IOpipe(
    io_pipe_token,
    plugins=[
        TracePlugin(),
        LoggerPlugin(enabled=True),
        EventInfoPlugin(),
        ProfilerPlugin(enabled=True)
    ]
)
```

**Comment by vincestus** [comment]
Same issue here.

**Comment by kolanos** [comment]
@majorgilles Thanks for the report. Does `IOpipe(debug=True, ...)` offer anything in the logs? The IOpipe agent should continue to log to CloudWatch.

**Comment by majorgilles** [comment]
> @majorgilles Thanks for the report. Does `IOpipe(debug=True, ...)` offer anything in the logs? The IOpipe agent should continue to log to CloudWatch.

I haven't had the time to investigate with debug=True, but will do so in a few days when our deadlines are reached

**Comment by kolanos** [comment]
@majorgilles Ok, thanks. What runtime are you using? Will test further on my end.

**Comment by majorgilles** [comment]
python 3.6

**Comment by majorgilles** [comment]
I'll update the ticket after our deadline is reached on wednesday if you have found no issue on your end

**Comment by kolanos** [comment]
Closing this as we're planning to phase out this plugin:

See: https://read.iopipe.com/enhanced-iopipe-observability-reducing-overhead-with-cloudwatch-logs-485f6bbc4af1
