### ISSUE TITLE
boto3 requests not being auto traced in 3.7

### ISSUE THREAD

**Issue by austinhuminski** [iopipe/iopipe-python#319]
**Description**

When using python3.7 runtime, requests made via `boto3` are not being auto traced. When changing the runtime to 3.6 it started tracing

**Steps to reproduce the issue:**

```
client = boto3.client('s3')
client.list_buckets()
```

**Describe the results you received:**
Nothing showing up in the tracing tab

**Describe the results you expected:**
The s3 call to list all buckets be auto traced

**Comment by kolanos** [comment]
It looks like botocore is no longer using `requests` and implements it's own HTTP wrapper now. Will need to reimplement/revise the monkey patching for newer versions.
