### ISSUE TITLE
Documentation is different than "Getting Started with IOpipe" screen

### ISSUE THREAD

**Issue by jonatasbaldin** [iopipe/iopipe-python#335]
Hi there 👋 

The docs from here are different than the "Getting Started with IOpipe" screen (the one presented when an account is created at IOpipe), as the screenshot shows:

![image](https://user-images.githubusercontent.com/8570364/60451615-c0e15e00-9c2c-11e9-90b1-7336ab62572c.png)

Like the import statement and the usage of the decorator.

Cheers!

**Comment by kolanos** [comment]
@jonatasbaldin Thanks for the report. Will make sure the getting started instructions are updated accordingly.

**Comment by kolanos** [comment]
Install page has been updated, thanks.

https://dashboard.iopipe.com/install
