### ISSUE TITLE
Performance: Simple Hello World function takes 500ms to execute when IOPipe wrapped

### ISSUE THREAD

**Issue by fastfiveoh** [iopipe/iopipe-python#56]
Customer report: A simple print("hello world") takes more than 500ms to execute (wrt to 20ms without IOpipe), which can get annoying (why should I pay 5x for my Lambda executions AND for your service as well?)

**Comment by adjohn** [comment]
Most likely due to not using a local API.  https://github.com/iopipe/iopipe-python/pull/61 adds support for regional collectors, so closing for now.
