### ISSUE TITLE
Disable agent if not running on Linux

### ISSUE THREAD

**Issue by kolanos** [iopipe/iopipe-python#97]
If the agent is running on OSX or some other OS it should disable itself to avoid raising errors while attempting to collect Linux-specific telemetry data.

**Comment by mislavcimpersak** [comment]
If no one objects, I could try to implement this in the next few days.

I could take advantage of a built-in: `sys.platform` ([py docs](https://docs.python.org/3/library/sys.html#sys.platform)) and raise a warning if it's not linux ie.

```
if not sys.platform.startswith('linux'):
    warning.warn('...')
```

and than disable IOpipe.

**Comment by kolanos** [comment]
@mislavcimpersak No objections. :)

We're planning some major updates to the Python agent in the upcoming months, but this and #96 will definitely be included.

**Comment by ewindisch** [comment]
We still report when using `sls invoke` and other "local invoke" mechanisms on NodeJS, and we've made this work on MacOS by having os-dependent functions (mostly replacing with mock values, currently)

It would be nice if we can do the same on Python!

**Comment by kolanos** [comment]
Here's the mock system in the node agent that @ewindisch  is referring to:
https://github.com/iopipe/iopipe/blob/master/src/mockSystem.js

I've started breaking out the system functions into a separate module similar to the way the node agent does it:
https://github.com/iopipe/iopipe-python/pull/98/files#diff-8fade00045091f378ca7f96cf522b080

I think an equivalent `mock_system` module would make sense.
